name: Python CI

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Pytest
        run: pip install pytest

      - name: Run Python Program
        run: |
          echo -e "99\n98\n95\n15\n40" | python marks.py

      